# -*- coding: utf-8 -*-
"""Fassion_MNIST_classifiers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oFzfrLoqpxtNXlV0JkZE8O9n4ZQl57u
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import cv2 as cv

(x_train,y_train),(x_test,y_test)= tf.keras.datasets.fashion_mnist.load_data()

x_train = x_train/255
x_test = x_test/255

print(x_train[10].min())
print(x_train[10].max())

from sklearn import svm

no_of_samples = len(x_train)

x_train = x_train.reshape((no_of_samples, -1))

clasi_svm = svm.LinearSVC(dual=False)
clasi_svm.fit(x_train,y_train)

x_test = x_test.reshape((len(x_test), -1))

pred = clasi_svm.predict(x_test)

from sklearn import metrics
print(metrics.classification_report(y_test, pred))

from sklearn.metrics import accuracy_score

accuracy_score(y_test , pred)

"""Prediction from test data"""

predict_1  = clasi_svm.predict(x_test[10].reshape(1,-1))

print(predict_1 , y_test[10])

"""Predction from google image"""

from matplotlib.pyplot import *

img_src = 'photo-1633966887768-64f9a867bdba.jpg'
im = cv.imread(img_src , 0)
imshow(im)

im = cv.resize(im ,(28,28))
print(im.shape)
imshow(im , cmap = 'gray')

print(clasi_svm.predict(im.reshape(1,-1)))

"""confustion matrix"""

conf_matrix = metrics.ConfusionMatrixDisplay.from_predictions(y_test,pred)

"""saving model"""

import pickle

pkl_file = "joblib_model.pkl"
with open(pkl_file , 'wb') as file:
     pickle.dump(clasi_svm, file )
